### ISSUE TITLE
OntDoc generated empty NI list

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/pyLODE#113]
If no Named Individuals are present, the docco doesn't link to the NI section in the ToC but the NI section is still present, and empty.

**Comment by hdelva** [comment]
There is a `{% if named_individuals|length > 0 %}` check in `document.html`, but I'm fairly certain this check should be in `named_individuals.html`instead. The `named_individuals`in `document.html` is the rendered HTML string, which contains the empty section.

**Comment by nicholascar** [comment]
Yes, I think it's a very easy fix. I'll get on to this issue, and probably a number of other small ones, in the next fortnight as I'm running a pyLODE development sprint for a project starting Monday.

Love PRs to directly fix any identified Issues of course so feel free to submit one for this!

**Comment by smarie** [comment]
That would be great!
