### ISSUE TITLE
Provide a `--version` command

### ISSUE THREAD

**Issue by smarie** [RDFLib/pyLODE#116]
It could be very useful to be able to do  `pylode --version` to quickly check that we are using the version we think we're using.
Note: of course I can get the version through pip or conda but it is less intuitive...

**Comment by VladimirAlexiev** [comment]
There is a `-v, --version` option but it fails for me: #119

**Comment by nicholascar** [comment]
This issue is now long (v2.9.x) solved in @VladimirAlexiev's case which is running the EXE binary on Windows
