### ISSUE TITLE
upgrading to 2.8.6

### ISSUE THREAD

**Issue by VladimirAlexiev** [RDFLib/pyLODE#120]
As you can see in #119, `pip install pylode` doesn't upgrade 2.8.5 to any later version.

So I got https://github.com/RDFLib/pyLODE/archive/refs/tags/2.8.6.zip and unzipped pylode.exe to `c:\Users\vladimir.alexiev.000\AppData\Local\Programs\Python\Python37\Scripts\`.

1) Trying to check version fails with a similar error to #119. 👎 
```
$ pylode -v
Traceback (most recent call last):
  File "pylode\cli.py", line 169, in <module>
  File "pylode\cli.py", line 108, in main
ImportError: cannot import name '__version__' from 'pylode' (C:\tmp\_MEI111002\pylode\__init__.pyc)
[2520] Failed to execute script cli
```

2) The Unicode problem is fixed, see #110  👍 

3) The exe file has grown from 110k to 12Mb, is this expected?

**Comment by nicholascar** [comment]
`pip install -U pylode` now installs 2.8.10.

I don't really know much about the Windows EXE version I'm afraid! I'm just blindly building it from a the pyinstaller script that someone else wrote (https://github.com/RDFLib/pyLODE/blob/master/pylode/pylode-cli.spec). I'd love any help with better configuring that script to produce better binaries...

**Comment by nicholascar** [comment]
Long since resolved so closing. Please reopen if continued issues.
