### ISSUE TITLE
add favicon

### ISSUE THREAD

**Issue by VladimirAlexiev** [RDFLib/pyLODE#123]
LODE has a favicon, PyLODE doesn't.
The favicon is very useful to let the user tell his browser tabs apart.

**Comment by nicholascar** [comment]
I've added favicons to the HTML templates with commit https://github.com/RDFLib/pyLODE/commit/d950a4d0e8e1f7b2713dac1a702e38d76b661e7e, so this will come through to PyPI in the next release (later tonight or tomorrow)
