### ISSUE TITLE
add TOC links or TOC navigation

### ISSUE THREAD

**Issue by VladimirAlexiev** [RDFLib/pyLODE#124]
It's very hard to orient yourself in a large ontology document, and to jump to another key place (the 3 indexes).
- LODE has links "back to ToC" or "Object Property ToC" (respectively "Class ToC", "Data Property ToC"). Example from: http://rawgit2.com/euBusinessGraph/eubg-data/master/ontology/_old/index.html (https://github.com/euBusinessGraph/eubg-data/issues/18)

![image](https://user-images.githubusercontent.com/536250/114860255-71195a00-9df4-11eb-98b6-b392659dfd85.png)

- I don't quite like the look (far right side), and the functionality is limited (it lets you jump but not orient yourself), but it's much better than nothing
- Some other TOC gadget could be better, eg a sidebar that shows in bold where you are

**Comment by nicholascar** [comment]
I've added a couple of links like LODE had - for the fragment URI of the Class/Property and a back to Class/Property Index.

Perhaps a left menu, collapsible TOC gadget like the W3C's reSpect docs have would be nice but I'm not sure I can do the necessary styling and JavaScript for that any time soon.

I'd love any offers of assistance for this task!

**Comment by nicholascar** [comment]
Added a whole ToC in 3.0.0, see https://rdflib.dev/pyLODE/examples/ontdoc/agrif.html
