### ISSUE TITLE
Support for Markdown in descriptions of properties

### ISSUE THREAD

**Issue by rybesh** [RDFLib/pyLODE#128]
Currently Markdown is supported in descriptions of classes but not of properties. It would be great if it were consistently supported for descriptions of any kind of entity.

**Comment by nicholascar** [comment]
@rybesh this would be easy to fix but could you put a PR in for it? There are so many consistency things that could be addressed but best if many eyes view the source code and improve it!

**Comment by nicholascar** [comment]
OK, I've gone and done this one with Commit https://github.com/RDFLib/pyLODE/commit/ae12537f3aeb71215587f21307faafd26176d3b2.

Perhaps Markdown support isn't consistent throughout pyLODE though, so I'll close this but love to see any PRs applying consistency!
