### ISSUE TITLE
Order of authors (`dc:creator`) is not preserved in the documentation

### ISSUE THREAD

**Issue by smarie** [RDFLib/pyLODE#132]
I noticed that the order in which the authors of an ontology are listed is scrambled (probably an alphabetical sorting?) when the html is built. Could this be an easy thing to fix ?

**Comment by nicholascar** [comment]
No, not easy to fix really, since RDF graphs are un-ordered. I _guess_ I could just sort them alphabetically but this might only be deterministic, rather than purely alphabetical, since decisions will have to be made about which properties to sort on.

**Comment by nicholascar** [comment]
Actually, the Creators and Contributors are already sorted - alphabetically by first name of the person or the start of an Org's name- so the field isn't _scrambled_, it's just likely different to whatever was added to the original RDF file.

So, I can't really solve this one unless a whole new ordering construct is added to the Creators and Contributors in an ontology, such as an RDF container - a sequence.

I'm going to close this but if @smarie you are really keen to preserve order for these agents, please raise a new Issue about supporting ordering components such as `rdf:Sequence` for multi-value properties.

**Comment by smarie** [comment]
Thanks for the feedback @nicholascar ! Let me come back to colleagues about this and we'll open an issue if needed

**Comment by niklasl** [comment]
You may find [`bibo:contributorList`](http://purl.org/ontology/bibo/contributorList) (and its subproperties `bibo:authorList` and `bibo:editorList`) useful for this specific purpose (intended to be used with RDF lists, like `<doc> bibo:authorList (<you> <me>) .`, or the more legacy `rdf:Seq` construct).

**Comment by smarie** [comment]
@nicholascar just reopening for the sake of continuing the discussion and to better understand what should be actually required in another ticket (or in this one if we rename it correctly)
