### ISSUE TITLE
Remove recommentations/allowance to use DC properties, only DCTERMS

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/pyLODE#135]
e.g. https://github.com/rdflib/pyLODE/#datatype---not-preferred

**Comment by dr-shorthair** [comment]
To support this: DCMI explicitly recommends only using `dcterms:` in an RDF context. 

 https://dublincore.org/specifications/dublin-core/dcmi-terms/#section-1

> In 2008, in the context of defining formal semantic constraints for DCMI metadata terms in support of RDF applications, the original fifteen elements themselves were mirrored in the /terms/ namespace.

>While the /elements/1.1/ namespace will be supported indefinitely, DCMI gently encourages use of the /terms/ namespace.

**Comment by nicholascar** [comment]
All recommendations removed in 3.x
