### ISSUE TITLE
Automate the inclusion of Overview diagram, caption and text

### ISSUE THREAD

**Issue by F3RR3T** [RDFLib/pyLODE#144]
PyLODE creates a stub `<div>` for Overview. At present, we just paste some stock html into the `<div>` that points to `images/overview.png` and  includes a caption. For the moment, in the ontology that I'm working on, I've  saved an 'include' file `images/overview.html` and then replace the 'overview' div with ` <div w3-include-html="images/overview.html"></div> `.

Issues #127 and #131 seem similar. 

Is there a way to automate this? I could not find a nice `dcterms:` property to handle this but perhaps there is something I haven't found?

**Comment by F3RR3T** [comment]
Example commit: https://github.com/AGLDWG/phs-ont/commit/54598a7b26a8e2665f6fb575db38dd549b3e240c

**Comment by nicholascar** [comment]
Can't really "fix" this as such. I like to keep an annoying grey box being auto-generated to prompt people to put in an image but we can't predict how they might generate an image and we're not auto-generating images, so it's really out of scope to make any real change here.
