### ISSUE TITLE
How to add picture to ontology

### ISSUE THREAD

**Issue by BonaBeavis** [RDFLib/pyLODE#149]
I know it is possible to add an picture to a class with `skos:example`. But how to add an picture representing the ontology replacing the "One picture says more than 1000 words" element?

**Comment by nicholascar** [comment]
@BonaBeavis sorry I've taken so long to reply to you, I've been consumed with lots of RDFlib work!

I like to leave that HTML in there to force people to consider an ontology image!

Probably the easiest thing is to replace that piece of HTML after generation either by hand - edit the HTML file directly - or with some small Python post-processing, if you're calling pyLODE from a script.

If you're using the command line, you will obviously not be able to post-process the HTML unless you write your own command line script for this.

If using Python, you could do this:

```python
m = MakeDocco(input_data_file="some-ontology.ttl")
html = m.document()
html_img = html.replace(
    '<div style="width:500px; height:50px; background-color: lightgrey; border:solid 2px grey; padding:10px;margin-bottom:5px; text-align:center;">Pictures say 1,000 words</div>',
    '<img src="fake.png" />'
)
open("some-ontology.html", "w").write(html_img)
```

Obviously that just puts the <img> tag in the right sput, but you'd actually have to have the `fake.png` image available!

I suppose you could also embed an SVG file directly in the HTML if you drew your ontology overview image in that...

Does this answer your question?

I've put a variant of the bove code in the test [test_issue_149.py](https://github.com/RDFLib/pyLODE/blob/master/tests/test_issue_149.py).

**Comment by nicholascar** [comment]
Closing as this has had an answer for about a month.
