### ISSUE TITLE
pypi release not tied to rdflib==6.0.0 ?

### ISSUE THREAD

**Issue by dwinston** [RDFLib/pyLODE#153]
I'm using rdflib 6.0.2, and I cannot `pip install pyLODE` because it requires `rdflib==6.0.0`. Could a new pypi release be pushed that works with rdflib>6.0.0? (it also could drop the rdflib-jsonld requirement if if requires rdflib>6.0.0, but that's a separate issue.)

**Comment by nicholascar** [comment]
I'm working on updating and making a release now. This should bypass PR #154

**Comment by chai3** [comment]
I think it will be fixed in version 2.13.0, but [it hasn't been released yet](https://pypi.org/project/pyLODE/#history).

**Comment by nicholascar** [comment]
I've pushed a very minor 2.13.0 to specifically deal with this issue. Apologies for the delay: time has been diverted to rdflib 6.1.0 release!

**Comment by nicholascar** [comment]
Fixed in 2.13.1
