### ISSUE TITLE
Anchor capitalization

### ISSUE THREAD

**Issue by hammar** [RDFLib/pyLODE#161]
Hi,

PyLODE generates anchors with a capitalization that is inconsistent with the class/property that the anchor concerns, e.g., `https://w3id.org/rec/core/OccupancyZone` gets the anchor `#Occupancyzone`. The anchors and links to them are internally consistent so the docs themselves work fine in isolation. But if I want to use HTTP content-type negotiation to redirect web browser users (looking for a particular class/property) to the appropriate segment of the documentation, it won't work.

Is this the intended behavior? If it is not, would you like for me to see if I can do something about it?

Best,

Karl

**Comment by nicholascar** [comment]
Hi @hammar please do have a go and fix this. I will eventually do another pyLODE sprint but you may be able to fix things before then! 

I'd love more contributions to this code base too, as new eyes would greatly improve it.

**Comment by hammar** [comment]
I realized just now when I was pinged on this that I never actually did work on this as you suggested. Sorry that I dropped the ball! And thanks for fixing it.

**Comment by smrgeoinfo** [comment]
There's still a problem... I have URIs with '_' characters in the final tokens (e.g. Geologic_Time_Interval), Pylode creates anchors with the same capitalization, but removes the '_', so my rewrite rules won't work (W3ID, Loop3d folder) unless I can remove the '_' somehow in the .htaccess file...

**Comment by smrgeoinfo** [comment]
I modified the pyLODE code to skip the anchor creation (fid) from the pref label and only use the code that creates anchor from the URI final toke.
