### ISSUE TITLE
Documentation on module usage

### ISSUE THREAD

**Issue by keski** [RDFLib/pyLODE#185]
The documentation for use as a module seems to be a bit outdated. 

```python
# Module Use

from pylode import OntDoc

# initialise
od = OntDoc(ontology="some-ontology-file.ttl")

# produce HTML
html = od.make_html()

# or save HTML to a file
od.make_html(destination="some-resulting-html-file.html")
```

In the current code base, shouldn't that be something like:

```python
# Module Use

from pylode.profiles.vocpub import VocPub
# or from pylode.profiles.ontpub import OntPub

# initialise
od = VocPub(ontology="some-ontology-file.ttl")

# produce HTML
html = od.make_html()

# or save HTML to a file
od.make_html(destination="some-resulting-html-file.html")
```

**Comment by nchauvat** [comment]
hi @edmondchuc and @nicholascar . Thank you for PyLODE. Is the project still actively maintained ? Looking at the commit history I would think it is, but I am surprised that an issue like this one has a MR that is not merged. Would you need help to review it ?
