### ISSUE TITLE
Cannot build Markdown documentation after pip install

### ISSUE THREAD

**Issue by scizzorz** [RDFLib/pyLODE#33]
I installed `pylode` via `pip` (technically via [poetry](https://github.com/sdispater/poetry), but that just uses `pip`), but I'm unable to build documentation successfully. I debugged a little and noted a few issues, but don't have an abundance of time to fix them and submit a PR myself:

* This absolute import (https://github.com/RDFLib/pyLODE/blob/master/src/pylode/cli.py#L7) should probably be changed to a relative import. I suspect it works when executing from that working directory which is why it's been unnoticed.
* `style.css` is not included in the distribution (https://github.com/RDFLib/pyLODE/blob/master/setup.py#L34)
* `*.md` templates are not included in the distribution (https://github.com/RDFLib/pyLODE/blob/master/setup.py#L34)

Happy to help test further to help you reproduce, and hopefully fix, these issues.

**Comment by scizzorz** [comment]
It might also be great to have a console script added to the `setup.py` so users can simply run `pylode`, rather than `python -m pylode.cli`: https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point

**Comment by nicholascar** [comment]
Thanks for the suggestions, I'll look into these.

There is a script to run pyLODE on the cli on Linux/Mac already, see https://github.com/RDFLib/pyLODE/tree/master/src/pylode/bin

**Comment by scizzorz** [comment]
Right, I had noticed that. It also didn't ship with the pyLODE distribution via pip, so I resorted to the module invocation. Including the existing script or adding a console script would be equally great.

**Comment by nicholascar** [comment]
Ensure that the pip distribution includes the cli

**Comment by koslambrou** [comment]
#52

**Comment by nicholascar** [comment]
Addressed and re-broken by a number of PRs but well and truly solved as of July 2020.
