### ISSUE TITLE
Generated Markdown is not rendered correctly 

### ISSUE THREAD

**Issue by scizzorz** [RDFLib/pyLODE#34]
Following on https://github.com/RDFLib/pyLODE/issues/33, after fixing some of these by manually copying files from the repo itself, I was able to build the markdown documentation. Unfortunately, the generated markdown tables didn't appear to render correctly in either the Sphinx + Recommonmark render nor the GitLab Markdown renderer. I think this is an issue with some markdown parsers disabling markdown parsing once HTML is detected, thus intermingled HTML and MD isn't accepted.

Lastly, I couldn't get a large majority of anchor links to work. This is observable even on GitHub's MD renderer: the **Delegated** link in the **Classes** section links to https://github.com/RDFLib/pyLODE/blob/master/src/pylode/examples/reg.md#Delegated, which does not anchor correctly.

**Comment by nicholascar** [comment]
OK, we may have to have options for pure Markdown and then Markdown + HTML or I might just have to learn how to replicate all the things that I've lazily added in to the Markdown in HTML in plain Markdown.

To be addressed after Issue #38.

**Comment by scizzorz** [comment]
Great, thanks! Glad to hear. re: #35, I think rST has its own separate systems for this as well.

**Comment by nicholascar** [comment]
OK, finally some real progress here! See these two documented versions of the AGRIF ontology in Markdown - OWL (as an ontology) & SKOS (as a taxonomy):

* https://github.com/RDFLib/pyLODE/blob/master/pylode/examples/agrif.md
* https://github.com/RDFLib/pyLODE/blob/master/pylode/examples/agrif.skos.md

The Markdown is much cleaner - far less HTML - but the fragment URIs still aren't working. that's the next thing to fix.

**Comment by nicholascar** [comment]
Markdown is cleaner but fragment URIs aren't completed, however there's a separate Issue for that (#86), so I'm closing this to focus on that URI Issue.
