### ISSUE TITLE
Create Windows executable 

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/pyLODE#41]
See if *pyinstaller* can do this

**Comment by jyucsiro** [comment]
See #42

**Comment by dr-shorthair** [comment]
See https://github.com/CSIRO-enviro-informatics/loci.cat/issues/45#issuecomment-579589882

**Comment by jyucsiro** [comment]
Also see PR #42

**Comment by nicholascar** [comment]
Done in https://github.com/RDFLib/pyLODE/commit/acd75acddcda32f953704c2c3f7854a837f633a2
