### ISSUE TITLE
Handle ORCIDs in dcterms:creator/contributor

### ISSUE THREAD

**Issue by dr-shorthair** [RDFLib/pyLODE#43]
Where the value of a `dcterms:creator` or `dcterms:contributor` is a URI, such as an ORCID, pyLODE is rendering "none". Better to put a hyperlink.

**Comment by nicholascar** [comment]
This has been handled for a long time now, e.g. http://linked.data.gov.au/def/geofeatures which uses the ORCID of two creators (me & John M.) to link our names, emails & affiliations.

What's missing is the ORCID image and link to the ORCID location itself! I've created Issue #58.
