### ISSUE TITLE
Add rendering for (named) individuals

### ISSUE THREAD

**Issue by dr-shorthair** [RDFLib/pyLODE#45]
Trying to use pyLODE to document a small controlled vocab. 
The individuals (only 11 of them) are not appearing in the generated documentation. 

source https://github.com/AGLDWG/asgs-ont/blob/master/asgs-cat.ttl

**Comment by dr-shorthair** [comment]
I suggest that any RDF resource whose `rdf:type` is anything other than `owl:*Property`, `owl:Class`, `owl:DeprecatedClass`, `rdf:Property`, `rdfs:Class`, `rdfs:Datatype`, should be rendered as an 'OWL Individuals' . This would include anything that is `owl:Thing`, owl:NamedIndividual`, `rdf:Statement`, `rdfs:Resource` and not also one of these classes.

**Comment by dr-shorthair** [comment]
#56 is the complementary issue

**Comment by nicholascar** [comment]
I've added a listing of Named Individuals now functionality. See AGRIF's new rendering for an example: 

* **http://linked.data.gov.au/def/agrif**

**Comment by nicholascar** [comment]
Actually, I've only added simple rendering of NIs catering for a few properties, not all the suggestions above (`rdf:Statement`, `rdfs:Resource` etc.) but will get there! Just need to do a few other pyLODE tasks first.
