### ISSUE TITLE
Add rendering for Datatypes

### ISSUE THREAD

**Issue by dr-shorthair** [RDFLib/pyLODE#46]
Datatype definitions are not showing in pyLODE documentation. 
e.g. https://github.com/AGLDWG/asgs-ont/blob/master/asgs-code.ttl

**Comment by nicholascar** [comment]
Can you find me a better ontology to test with? I can only see 1 x ^^rdf:HTML & 1 x ^^xsd:boolean in that ont.

**Comment by dr-shorthair** [comment]
Sorry - https://github.com/AGLDWG/asgs-ont/blob/master/asgs-code.ttl is deprecated. I should have pointed you at https://github.com/AGLDWG/asgs-ont/blob/master/asgs-id.ttl

It also has a bunch of additional axioms (constraints) for classes that are primarily defined in one of the imports ...

**Comment by nicholascar** [comment]
@dr-shorthair if your interest is in pretty HTML for ORCID, as per:

```
dcterms:creator "<a href='https://orcid.org/0000-0002-3884-3420'>Simon J D Cox, CSIRO</a>"^^rdf:HTML ;
```

Then try the 2.1 release of pyLODE now as it caters for ORCID logo when an ORCID for a person is used, see the [example AGRIF output](https://raw.githack.com/RDFLib/pyLODE/master/pylode/examples/agrif.html).

This means you characterise a person as 

```
dcterms:creator <https://orcid.org/0000-0002-3884-3420> ;
...
<https://orcid.org/0000-0002-3884-3420>
    a sdo:Person ;
    sdo:name "Simon J D Cox" ;
    sdo:affiliation <http://linked.data.gov.au/org/csiro> ;
    ...
```
...which is orders of magnitude better Semantic Web data than jamming HTML microformat into `dcterms:creator`

**Comment by dr-shorthair** [comment]
Indeed. The `rdf:HTML` was a stop-gap. It is appropriate for things like `dc:description` and `skos:definition` but a poor facsimile of structured data elsewhere.

**Comment by nicholascar** [comment]
So I think we are close to being able to bypass all the cases you have been using the embedded HTML for. If you can list all the cases (Agent links + ORCID; text markup (descriptions) then I'll check off the ones we can bypass and close this when all are done.

**Comment by dr-shorthair** [comment]
Does this discussion belong in #30 ?

**Comment by nicholascar** [comment]
OK, well closing this as the main issue - handling/bypassing of links - is done and leaving #30 open to deal with rendering HTML for formatted text.
