### ISSUE TITLE
Add rendering for skos:example

### ISSUE THREAD

**Issue by dr-shorthair** [RDFLib/pyLODE#48]
`skos:example` is a good place for inline code examples within Ontology documentation. 
e.g. https://github.com/CSIRO-enviro-informatics/geosparql-ext-ont/blob/master/geox.ttl

**Comment by nicholascar** [comment]
Addressed in [release 1.8](https://github.com/RDFLib/pyLODE/releases/tag/1.8).

Windows binary not rebuilt.

**Comment by nicholascar** [comment]
This is demonstrated in a now updated GeoX Ontology: <http://linked.data.gov.au/def/geox>

**Comment by dr-shorthair** [comment]
> Addressed in [release 1.8](https://github.com/RDFLib/pyLODE/releases/tag/1.8).
> 
> Windows binary not rebuilt.

@jyucsiro is it trivial to rebuild the windows binary?

**Comment by jyucsiro** [comment]
@dr-shorthair it's trivial for me to rebuild it. See attached zip file below.

it would be worth thinking about using a continuous build process like Travis. It supports building windows binaries - see https://docs.travis-ci.com/user/reference/windows/

[pylode.zip](https://github.com/RDFLib/pyLODE/files/4340742/pylode.zip)
