### ISSUE TITLE
pylode.exe broken

### ISSUE THREAD

**Issue by dr-shorthair** [RDFLib/pyLODE#51]
The link to pylode.exe here https://github.com/RDFLib/pyLODE#use does not find anything

**Comment by dr-shorthair** [comment]
Probably related to #61

**Comment by dr-shorthair** [comment]
@jyucsiro rebuilt the windows exe - see https://github.com/RDFLib/pyLODE/issues/67#issuecomment-630628356 but it is throwing the following error:

```
No module named 'rdflib_jsonld.serializer'
Traceback (most recent call last):
  File "pylode\makedocco.py", line 174, in document
  File "pylode\docprofile_owlp.py", line 1275, in generate_document
  File "pylode\docprofile_owlp.py", line 1090, in _make_document
  File "pylode\docprofile.py", line 363, in _make_schemaorg_metadata
  File "site-packages\rdflib\graph.py", line 961, in serialize
  File "site-packages\rdflib\plugin.py", line 107, in get
  File "site-packages\rdflib\plugin.py", line 69, in getClass
ModuleNotFoundError: No module named 'rdflib_jsonld.serializer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pylode\cli.py", line 204, in <module>
  File "pylode\cli.py", line 189, in main
  File "pylode\makedocco.py", line 177, in document
Exception: The file you specified as 'destination' could not be written to.
[43136] Failed to execute script cli
```

**Comment by dr-shorthair** [comment]
Broken again :-( some library keeps getting not included ... (Nick rebuilt it #61)
![image](https://user-images.githubusercontent.com/608303/83084082-48e51780-a0cb-11ea-9a87-fbccd043839e.png)

**Comment by nicholascar** [comment]
Oh, I think this isn't that a library's not being included (since I'm using the same spec file for the EXE as @jyucsiro) but that there's a problem with the way paths are bing handled within code - it seems unable, in Windows or Mac or Linux - to write to a directory other than current. So try running the EXE from the directory that the RDF file is in, i.e.

```
pylode.exe -i /some/path/input.rdf -o output.rdf
```
(no paths for the -o data)

This will mean adding pylode.exe to windows PATH so you can access it anywhere.

Yes, a work-around until this works:

```
pylode.exe -i /some/path/input.rdf -o /some/other/path/output.rdf
```

**Comment by dr-shorthair** [comment]
I did that first, and just tried again without paths And if you look at my CL you'll see that I'm sitting in the directory where it is. 

@jyucsiro managed to overcome this problem last week when he rebuilt it for me.

**Comment by nicholascar** [comment]
OK, I might call Jonathan and ask about this then as I can't work out the issue!

**Comment by jyucsiro** [comment]
Hi all, apologies. meant to push a PR. here it is:
https://github.com/RDFLib/pyLODE/pull/76
