### ISSUE TITLE
namespaces not found in imports from rdflib.namespace

### ISSUE THREAD

**Issue by Simo-climb** [RDFLib/pyLODE#59]
Howdy

I just pulled the latest version and when trying to run I got errors saying that PROV, and SDO names were not found in the rdflib package namespace.py.

On inspection is does seem they are absent in that script..... but don't trust my noob python skills.

Received the following error in pycharm

```
Traceback (most recent call last):
  File "C:/Users/simon/Documents/GitHub/pyLODE/pylode/cli.py", line 7, in <module>
    from makedocco import MakeDocco
  File "C:\Users\simon\Documents\GitHub\pyLODE\pylode\makedocco.py", line 7, in <module>
    from docprofile_owlp import Owlp
  File "C:\Users\simon\Documents\GitHub\pyLODE\pylode\docprofile_owlp.py", line 5, in <module>
    from rdflib.namespace import DC, DCTERMS, DOAP, OWL, PROV, RDF, RDFS, SDO, SKOS
ImportError: cannot import name 'PROV' from 'rdflib.namespace' (C:\Users\simon\AppData\Local\Programs\Python\Python38\lib\site-packages\rdflib\namespace.py)
```

And perhaps related....... I was unable to run the windows executable and maybe this was why.  There is an error message in the windows executable pop up window but it disappears too fast to capture it soz.

Cheers

Simon

**Comment by nicholascar** [comment]
> On inspection is does seem they are absent in that script

Hi @Simo-climb sorry, my bad: sorry but I've been using the latest rdflib release (`master` branch code), not the stable rdflib 4.2.2 as on PyPI. rdflib 5.0.0 was release yesterday (!!) and that *does* contain SDO & PROV so if you pip update your rdflib to 5.0.0, this issue should go away.

Please let me know if this is the case and close this Issue: I really want to make sure pyLODE s working well with the new rdflib release.

> I was unable to run the windows executable...

I'll have to get to that next. I haven't been rebuilding the Windows EXE in step with the pyLODE updates (laziness/time) so I've still got to figure out how to get that done. If we can solve the above issue, let's tackle the Windows EXE next.

Thanks for all the feedback by the way, Nick

**Comment by Simo-climb** [comment]
Thanks Nick

Yep updating rdflib to 5.0.0 resolved this.

S
