### ISSUE TITLE
need to refactor cli.py to reflect updated docprofiles filename and PYLODE_owl and skos profiles

### ISSUE THREAD

**Issue by Simo-climb** [RDFLib/pyLODE#63]
Hey Nick

looks like you need to adjust the filename reference of profiles to docprofiles in cli.py to correctly reference docprofiles.py.

Also within docprofiles.py you have added the prefix PYLODE_ to the owl and skos profiles, so these also require updating in cli.py

need to change line 8 in cli.py 
from

`from profiles import OWL_PROFILE, SKOS_PROFILE`

to

`from docprofiles import PYLODE_OWL_PROFILE, PYLODE_SKOS_PROFILE`

Cheers

Simon

**Comment by nicholascar** [comment]
Done, as of a commit a few hours ago. I'll just push a full release to PyPI & GitHub now.

**Comment by nicholascar** [comment]
https://pypi.org/project/pyLODE/2.1/

**Comment by Simo-climb** [comment]
cool.
