### ISSUE TITLE
throws an error because of "import .makedocco import *" 

### ISSUE THREAD

**Issue by businessabstraction** [RDFLib/pyLODE#64]
Whether you want import pylode into Python, or execute pylode (in this case, under Linux), it throws an error.
Python 3.7

**Comment by nicholascar** [comment]
Thanks for the note @businessabstraction (Alex!). I've really struggled with getting Python 3 imports correct for both the CLI scripts and the Python modules and clearly haven't solved everything yet.

I'll try and fix this ASAP.

Would love a Pull Request if you can suggest a working formula...

**Comment by nicholascar** [comment]
I have pushed a new release of this code both here to GitHub and also to PyPI ([2.2](https://pypi.org/project/pyLODE/2.2/) and hopefully now all import issues are solved. Please check and, if they are, close this Issue.

**Comment by koslambrou** [comment]
Seems related, but after installing pylode with `python3.7` and running `pylode`:

```
$ python -m venv .venv
$ source .venv/bin/activate
$ pip install pylode # Installs pylode-2.2
$ pylode
Traceback (most recent call last):
  File ".../.venv/bin/pylode", line 6, in <module>
    from pylode.cli import main
  File ".../.venv/lib/python3.7/site-packages/pylode/cli.py", line 7, in <module>
    from makedocco import MakeDocco
ModuleNotFoundError: No module named 'makedocco'
```

**Comment by nicholascar** [comment]
@koslambrou OK, I've just replicated that and will try and solve now. So many import issues...

**Comment by smarie** [comment]
I'll try to help with a PR

**Comment by nicholascar** [comment]
I've overcome all the import issues but haven't implemented the `__all__` directives - would love a hand with that! Will close this now though as the main import issues are done.
