### ISSUE TITLE
skos:example need to be formatted as <code>

### ISSUE THREAD

**Issue by dr-shorthair** [RDFLib/pyLODE#67]
The contents of `skos:example` must be escaped using 
\```
`formatted example code here`
\````
in the **Markdown** version, or 
\<code> formatted example code here \</code> 
in the **HTML** version

**Comment by dr-shorthair** [comment]
Or maybe <pre>

**Comment by nicholascar** [comment]
Addressed by https://github.com/RDFLib/pyLODE/commit/66c58c1c76d3cc22ea44d1aa4311d84b860377a2

This was quite hard to work out for Markdown! Super easy for HTML...

**Comment by dr-shorthair** [comment]
Yeah - Markdown table formatting is very limited. You have to embed HTML \<br/\>to make any sense.

**Comment by dr-shorthair** [comment]
(Now just need someone to regenerate the Windows .exe for me ... - @jyucsiro ?)

**Comment by jyucsiro** [comment]
@dr-shorthair just updated to the latest version on master. See link below:
[pylode.zip](https://github.com/RDFLib/pyLODE/files/4648756/pylode.zip)

**Comment by jyucsiro** [comment]
@dr-shorthair try again. addressing #51 
[pylode.zip](https://github.com/RDFLib/pyLODE/files/4654085/pylode.zip)
