### ISSUE TITLE
Alphabetical order of elements?

### ISSUE THREAD

**Issue by carueda** [RDFLib/pyLODE#71]
First off, great tool.

While testing an installation of pyLODE for the COR today, I just note that the order of list elements is not "consistent".  

Example with http://cor.esipfed.org/pylode?url=http://sweetontology.net/phenAtmo and only paying attention to the imports:

>![image](https://user-images.githubusercontent.com/556505/81350915-e5416e80-9077-11ea-80f7-e1e92396abd6.png)

Just reload the page and you're likely to get a different order:

>![image](https://user-images.githubusercontent.com/556505/81350950-fab69880-9077-11ea-8148-f4e2bbab172a.png)

Of course, the different order doesn't mean anything wrong with the semantics, but for UX purposes the suggestion here is to consider incorporating some consistent order in listings, say, alphabetically.

**Comment by nicholascar** [comment]
Yes, I suppose most of the ontologies don't have very long lists of things like imports so this hasn't come up yet, but SWEET sure does so here's the issue! I guess there's noting preventing the addition of ordering so I'll try and put a `sort()` in there to fix this and will come back to this issue when I do.

**Comment by nicholascar** [comment]
Addressed by Commit https://github.com/RDFLib/pyLODE/commit/2dc06c4ba9677d2863fe7206da410b95e0ef9ed7
