### ISSUE TITLE
Incorrect base in URL to "Ontology RDF"

### ISSUE THREAD

**Issue by carueda** [RDFLib/pyLODE#73]
When an ontology is dispatched via an explicit pylode service (that is, not via some proxy mechanism, see below), e.g.:

http://cor.esipfed.org/pylode?url=http://sweetontology.net/matr

the "Ontology RDF" link turns out pointing to the location where the pylode service itself is running, 
`http://cor.esipfed.org/matr`, which is incorrect:

![image](https://user-images.githubusercontent.com/556505/81965675-3e0b8c80-95cd-11ea-9031-4cec6a86cfc8.png)

It seems the service location is somehow being taken as the "base" for the ontology.

----
> BTW, just as a side note, since the the SWEET ontology URLs are transparently proxied to the pylode service (when content-negotiation indicates HTML dispatch), a direct display of http://sweetontology.net/matr works ok:
>  ![image](https://user-images.githubusercontent.com/556505/81966377-54661800-95ce-11ea-923a-e21ac3fa2e54.png)

**Comment by nicholascar** [comment]
I think I've fixed this with Commit https://github.com/RDFLib/pyLODE/commit/83e5dd17396a969e84cdadb799e92ee5656d1bb8.

Basically, if the ontology's source is a URI, as it always us when using the Falcon server, use that as the RDF source's location. If it's a file, use that.

**Comment by carueda** [comment]
thanks @nicholascar !

 @lewismc let's keep this in mind for verification when the pylode instance @ COR is updated.
